### ISSUE TITLE
GTK4 port?

### ISSUE THREAD

**Issue by joshmmlx** [uowuo/abaddon#60]
Running latest vcpkg, but apparently abaddon is based upon <GTK4 and <libsigc++3. Latest vcpkg pulls GTK4 and libsigc++3. I was able to modify the libsigc++ conflicts since it's a simple syntactic change fixable with a bunch of find replace operations (https://www.murrayc.com/permalink/2016/03/17/libsigc-stdfunction-style-syntax/), but as I tried to implement GTK4 style menu items I gave up.

If you don't have plans, what git version of vcpkg are you running so I can downgrade to the correct packages? Ttrying to compile this on x86/i686.

**Comment by ouwou** [comment]
currently it uses microsoft/vcpkg@a9b27ed5dffbf70b135eddb0c4729f3ca87f106c but as of a couple days ago i dont think that will work because some of the msys packages it tries to pull are so old they 404. ive been trying to move to msys2 and will probably finalize that very soon, you can try that from the [msys branch](https://github.com/uowuo/abaddon/tree/msys).

switching to gtk4 would be a pretty big thing to try and do and its something i looked into. its not stable as a cross-platform gui framework right now (at least not as stable as gtk3) and i wouldnt be using the c++ bindings since [its probably going to be abandoned](https://gitlab.gnome.org/GNOME/gtkmm/-/issues/110#note_1374975) (also gtkmm is basically hand-written and lacks a lot of the API since it was first developed before gobject-introspection which would make a lot more sense to use now).

anyways try the msys branch and if you run into any other issues feel free to open another issue for that

**Comment by joshmmlx** [comment]
Thanks for the github version, you can probably get away with using the latest msys install that vcpkg uses, just modify C:\dev\vcpkg\scripts\cmake\vcpkg_acquire_msys.cmake to the latest. I actually had to custom write my own because I am compiling on an x86 machine and vcpkg pulls the x64 msys repo. Trying to build this for a retro laptop (>10 years old) because Discord is simply unusable on it. Should install Linux but I've yet to find a stable distro.

Thanks again!

**Comment by poudink** [comment]
stable distros aren't very hard to find. you know, debian stable, ubuntu lts, mint lts, etc

**Comment by joshmmlx** [comment]
I built it for 32 bit (on a 32 bit host, lol): https://github.com/joshmmlx/abaddon/releases/tag/v0.1.4

Works very well, 30 megs of ram as opposed to the 500 megs it would take to load Discord in Chrome/Firefox. Brought new life to this retro laptop. :)

**Comment by ouwou** [comment]
nice, though i dont see anything uploaded there. and btw if you were to have gotten it to build with gtk4, the memory usage would have been very bad. idk why but gtk4 eats so much memory on windows.

**Comment by joshmmlx** [comment]
Oops, Pale Moon browser didn't attach it properly. Fixed now. Also, abaddon will use up a gargantuan amount of ram in fast order on a slow system if you scroll too fast with lots of images and media files present, but I believe that is a cache writing thing on slow systems.

I tried figuring out a way to pattern the new GTK4 menu items with yours but I couldn't, there's other projects that wrote scripts to help them do it but yeah, a bit beyond me. I did notice while going over the code your comment about c time conventions lol...

**Comment by ouwou** [comment]
>lots of images and media files

yeah this is particularly bad when there are gifs because it will try and load the entire gif and just display the first frame, and gif decoding is really really memory intensive in gtk (at least on windows). i think it uses wingdi which probably isnt the most efficient api. for instance open the emoji list in a server with a good amount of animated emojis and it uses a stupid amount of memory. i dont really know what to do about that. i guess for messages i can probably modify the url a bit to get a smaller file from discords cdn

**Comment by ouwou** [comment]
putting aside how much id have to rewrite, gtk4 still isnt in a very good place imo. i would like to benefit from the increased responsiveness/snappiness buuutttt i still find it too unstable to use. it has significantly higher memory usage + has bad memory leaks and for example u can segfault the gtk4-demo reliably in about 5 seconds :P

**Comment by Malix-Labs** [comment]
Can this be reconsidered?

gtkmm hasn't been abandonned and gtk4 is now stable

**Comment by orowith2os** [comment]
Peel is an option for newer GIR-based bindings, and can interoperate with older gtkmm code (provided it's the same GTK version): https://gitlab.gnome.org/bugaevc/peel/
